### ISSUE TITLE
Make games parallel

### ISSUE THREAD

**Issue by sergeychernyshev** [shareholdergame/shareholdergame-ui#17]
Allow for playing A & B games of the same pair (and more games, in case of more than 2 users) to run in parallel for faster gameplay.

**Comment by alexsavin** [comment]
It is completely backend task. It should be moved to shareholdergame-core repository.

**Comment by sergeychernyshev** [comment]
Are there any visual cues that are needed for that? or do we already have that in UI and we just need to spawn them upon activation and that's it?

**Comment by sergeychernyshev** [comment]
Can you create one with details of what to be done on backend and we'll just link it from here.

**Comment by alexsavin** [comment]
https://github.com/shareholdergame/shareholdergame-core/issues/1
