### ISSUE TITLE
Create game archive page

### ISSUE THREAD

**Issue by alexsavin** [shareholdergame/shareholdergame-ui#19]
![6-game-archive-page](https://user-images.githubusercontent.com/38076/37568754-d56986e4-2aaf-11e8-8675-12eaed639286.png)
https://gist.github.com/alexsavin/9d38be4da758849a9f3409f538bd863e#file-6-game-archive-page-png

**Comment by sergeychernyshev** [comment]
@alexsavin, what does "published" games mean on this screen?

**Comment by sergeychernyshev** [comment]
It looks like here, a set of the games is displayed as one entry, e.g. A+B for 2 players and A+B+C+D+E+F+G for 6 players.

Looks like these are better off if results are displayed vertically, and not horizontally - I'll try to create it and we'll see.

**Comment by alexsavin** [comment]
"Published" it's a new functionality that was planned to be introduced in 1.6. Now player can see only games that he played but users asked me to add possibility to see other games if players give access to them.
The proposal is here http://forum.stockholdergame.com/showthread.php?tid=114

**Comment by alexsavin** [comment]
Lets try to display vertically maybe it will look better.

**Comment by sergeychernyshev** [comment]
Yep, that's probably the way to go, I'll work on that.

That being said, some of this is not completely clear, e.g. where do users go when they click "View" in case when set contained multiple games.

**Comment by sergeychernyshev** [comment]
So, this is a mockup for player listing and their scores:
![game-archive-item](https://user-images.githubusercontent.com/38076/37770386-a61bf1ee-2daa-11e8-9bbe-f7c6e6271178.png)

I'll need to think what happens when there is a different number of players in different sets and height of those boxes becomes different... still think vertical is better

**Comment by sergeychernyshev** [comment]
BTW, it's not clear which games would the user see in the published tab - is that everybody's games that were published? e.g. search for everybody's non-private games?

**Comment by alexsavin** [comment]
> where do users go when they click "View"
This will be a special page. Now it is a dialog opened by click on link "Game series result".
> what happens when there is a different number of players in different sets and height 
Oh I understand the issue! Maybe apply a sorting by number of players by default? This issue is actual only for "Other" filter.
> which games would the user see in the published tab
In 1.6 I planned to implement highest level of sharing - everybody who signed in can see published games. FMPV it makes sense to provide users possibility to share game for limited number of users.
